### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#18] opened 2023-09-18 15:15 UTC
On access form submission, send data to mailchimp to a list 

Need to map form fields to mailchimp list fields

Ask client

1. This is something they want to do
2. Which list it should be sent to
3. API Key setup for sending data to mailchimp

**Comment by allenkyee** [comment] 2023-09-18 18:07
can u leave the emails being added to mail chimp to end? I still need to confirm they want this...they might not even want it

**Comment by allenkyee** [comment] 2023-09-19 14:19
They have confirmed that they want the email submissions to go to “Education” audience in mail chimp

**Comment by asierrajr** [comment] 2023-09-27 13:56
Some. notes: 

For testing, do no permanently delete the contact you push up. Just archive and I believe if you push up it should re enable.
Here is why: 
https://stackoverflow.com/questions/52198510/mailchimp-resubscribe-a-deleted-member-causes-the-api-to-return-a-400-bad-reques

https://mailchimp.com/help/delete-contacts/

I created a mailchimp audience list for development so we are not manipulating the live list too much

**Comment by asierrajr** [comment] 2023-09-27 20:29
I am not able to pass the Zip Code
It fails validation and requires a more complete address. 
The tried setting everything to empty but the zipcode but it puts the Zip in the city field

```
"ADDRESS" => [
              "addr1" => "",
              "city" => "",
              "state" => "",
              "zip" => "12345"
            ]
```
For now I am not passing this information.  Confirm this is ok

**Comment by allenkyee** [comment] 2023-09-27 20:44
Client is ok with collecting state instead of Zip

**Comment by asierrajr** [comment] 2023-09-27 21:01
I have to check what is possible.

**Comment by asierrajr** [comment] 2023-09-28 04:08
So for the Address field that comes with mailchimp, we are required to set addr1, city, state, and zip.
I tested this and it's in the documentation after doing research

We can add a custom field to the audience, which Mailchimp calls "Merge Fields"
https://mailchimp.com/developer/marketing/docs/merge-fields/

There is a zip code field type available but it only works for US Zipcodes. May need to use a text field.

I rather use Zip Code since it's easier to manage. 

Let me know if client is interested in creating a custom field for Zip Code

The configs is for individual audience list and the development one I created would be here
https://us2.admin.mailchimp.com/lists/settings/merge-tags?id=978214

**Comment by asierrajr** [comment] 2023-09-28 04:14
As for what's on Staging right now related to ticket #19 

https://staging-education.mjhnyc.org/signup/?redirect_to=4109

On Submit, Email, First Name and Last Name are being pushed to Mailchimp to the MJH Web App Development Audience

This is managed via a custom mailchimp settings found
https://staging-education.mjhnyc.org/wp/wp-admin/options-general.php?page=mjh-Mailchimp-settings

**Comment by allenkyee** [comment] 2023-09-28 17:05
added multiple signups, none of the emails are saving into Mail chimp

**Comment by asierrajr** [comment] 2023-09-29 00:20
Added the merge field "ZIP" in mailchimp audience I created and it's now passing and collecting the zip/postal code

**Comment by allenkyee** [comment] 2023-09-29 15:37
going to close this since info adding to mail chimp is working well

**Closed as completed by allenkyee** 2023-09-29 15:37 UTC
